# Generated by Django 5.1.1 on 2024-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boulder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date_set", models.DateTimeField(auto_now_add=True)),
                ("grade", models.IntegerField()),
                ("holds_hands_only", models.JSONField()),
                ("holds_feet_only", models.JSONField()),
                ("holds_general", models.JSONField()),
                ("holds_finish", models.JSONField()),
                ("holds_start", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
            ],
        ),
    ]
