# Generated by Django 5.1.1 on 2024-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boulders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boulder",
            name="holds_feet_only",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="holds_finish",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="holds_general",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="holds_hands_only",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="holds_start",
            field=models.JSONField(default=list),
        ),
    ]
