# Generated by Django 5.1.1 on 2024-10-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boulders", "0002_alter_boulder_holds_feet_only_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boulder",
            name="holds_feet_only",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="holds_general",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="boulder",
            name="holds_hands_only",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
