# Generated by Django 5.1.1 on 2024-10-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boulders", "0003_alter_boulder_holds_feet_only_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boulder",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
