# Generated by Django 5.1.1 on 2024-11-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boulders", "0004_boulder_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boulder",
            name="grade",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
