# Generated by Django 5.1.1 on 2024-11-17 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boulders", "0005_alter_boulder_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("date_set", models.DateTimeField(auto_now_add=True)),
                ("grade", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Circuit",
                "verbose_name_plural": "Circuits",
            },
        ),
        migrations.CreateModel(
            name="CircuitSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "boulder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boulders.boulder",
                    ),
                ),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="boulders.circuit",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("circuit", "order")},
            },
        ),
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.AddField(
            model_name="circuit",
            name="sections",
            field=models.ManyToManyField(
                related_name="circuits",
                through="boulders.CircuitSection",
                to="boulders.boulder",
            ),
        ),
    ]
