# Generated by Django 5.1.1 on 2024-11-21 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boulders", "0007_climberprofile_circuitascent_boulderascent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="climberprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="climber_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
